[package]
name = "typikon"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = { version = "0.10.0", default-features = false, features = ["html"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
colored = "2.0"