book:
  title: 现代 Java 编程指南
  author: Leon Ding
  description: 一本基于 JDK21 版本讲解 Java21 新特性编程实践书籍，采用 WSL + VSCode 作为基础开发环境。
  language: zh-cn # 语言设置
  theme: default # 主题设置
 
highlight:
  - C
  - Java
  - Rust
  - JavaScript
  - SQL

directory:
  theme: theme # 主题目录
  source: book # 源文件目录
  output: docs # 渲染输出目录

nav:
  path: root.yaml # 目录映射文件

theme:
  name: typikon                # 自定义网站主题
  custom_css:                      # 自定义 CSS 文件
    - assets/light-theme.css     
    - assets/dark-theme.css
    - assets/sidebars.css
  custom_js:                       # 自定义 JS 文件
    - assets/sidebars.js           
    - assets/google-analytics.js     

markdown:
  extensions:
    - markdown.extensions.extra
    - markdown.extensions.codehilite
    - markdown.extensions.toc
  output:
    format: html # 输出格式

deployment:
  provider: github-pages # 部署方式
  repository: git@github.com:auula/typikon.git # 仓库地址
  branch: gh-pages # 分支

