settings:
  about:
    title: Typikon Book
    author: Leon Ding
    description: Typikon name derived from Typikon Book, the a static website rendering tool similar to mdbook and hugo, but it focuses only on rendering markdown into an online book, and is easier to use than the other tools.
    language: zh-cn
    keywords: typikon,book,website,generator,static,html,css,js,theme,rust

  directory:
    theme: theme
    source: book
    output: docs

  theme: typikon-theme

  deployment:
    repository: git@github.com:auula/typikon.git

  custom_css:
    - assets/light-theme.css
    - assets/dark-theme.css
    - assets/sidebars.css

  custom_js:
    - assets/sidebars.js
    - assets/google-analytics.js
