name: Rust CI

on:
  push:
    branches:
      - main
      - dev  # 在 push 到 main 或 dev 分支时触发
  pull_request:
    branches:
      - main
      - dev  # 在拉取请求到 main 或 dev 分支时触发

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Cargo Tarpaulin 
      run: cargo install cargo-tarpaulin    
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo-tarpaulin
      run: cargo tarpaulin --out Xml
    - name: Run cargo-audit
      run: cargo install cargo-audit  && cargo-audit audit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  
